### ISSUE TITLE
better emerge sync

### ISSUE THREAD

**Issue by axease** [MattiaG-afk/gentoo-ohmyzsh#2]
when use `sudo emerge --sync` will not update eix local cache

i want better just `sudo eix-sync`

god bless you.

**Comment by MattiaGaspa** [comment]
Thank you for the suggestion!
I added the command, with something more. Feel free to correct (and/aor PR) any error because I haven't used Gentoo/ohmyzsh in a while and I don't remember everything.

Thank you again and happy holidays
